export const siteContent = {
  music: "/WoTW.mp3",
  musicVolume: 0.55,
  envelopeTo: "for Baby Angel",
  greetTitle: "Happy birthday, Mi Casa.",
  greetLede: [
    "It's your birthday and I'm not there, which is the one thing about today I'd fix if I could.",
    "So I gathered a few pieces of our little world. The calls, the silly faces, the places we can meet even from far away. Stay a while.",
  ],
  photos: [
    { file: "memories/memory-1.webp", width: 720, height: 1280, alt: "A playful pout while lying on a pillow.", caption: "Even your little pout deserves its own save file." },
    { file: "memories/memory-2.webp", width: 720, height: 1280, alt: "A portrait with two braids and a playful expression.", caption: "Two braids. One very unfair amount of cute." },
    { file: "memories/memory-3.webp", width: 720, height: 1280, alt: "A relaxed portrait in a pale blue shirt with braided hair.", caption: "No grand occasion. Just you, and that is enough." },
    { file: "memories/memory-4.webp", width: 949, height: 1800, alt: "A close-up portrait tucked beside a soft gray pillow.", caption: "A little corner of the screen, a whole lot of my attention." },
    { file: "memories/memory-5.webp", width: 1080, height: 1427, alt: "A close-up selfie with a warm vintage camcorder filter.", caption: "You already look like a memory I will keep for years." },
    { file: "memories/memory-6.webp", width: 828, height: 1792, alt: "A phone video call with two people resting on their pillows.", caption: "Different pillows. The same quiet moment." },
    { file: "memories/memory-7.webp", width: 1600, height: 1041, alt: "A desktop video call showing a person relaxing with their phone.", caption: "Even when we do our own thing, I like having you there." },
    { file: "memories/memory-8.webp", width: 472, height: 790, alt: "A sleepy close-up beside a patterned pillow during a call.", caption: "The conversation gets quieter. I stay a little longer." },
    { file: "memories/memory-9.webp", width: 1600, height: 1041, alt: "Two game avatars sitting together beneath a blue sky.", caption: "Until we can sit together for real, save me the spot beside you." },
    { file: "memories/memory-10.webp", width: 822, height: 1200, alt: "A close-up with a playful hand pose around one eye.", caption: "One more silly face. One more reason this album is yours." },
  ],
  greetClose: [
    "Have the best day. Eat the McFlurry. Drink the ice lemon tea.",
    "I hope it's a good one, Angel.",
  ],
  lockHint: "This one's locked. The password is the night it started.",
  passwords: ["1111111", "11110111", "1111", "111111", "1111111111"],
  wrongMsg: "Not that one. Think of the date.",
  slots: [
    "You fell asleep on call so many times that I stopped hanging up. I'd just leave it running until morning.",
    "Antarctica Expedition. You clearing the parkour like it's nothing while I'm still stuck on the second jump.",
    "“Can you help with my assignment?” Every time, usually near midnight. I said yes every time. I'd say yes again.",
    "McFlurry and ice lemon tea. One day I'm buying you both in person, and that's the whole plan.",
    "Serious on a call with your lecturer, then jedag jedug on TikTok ten minutes later, then a whole Chinese drama in a weekend. All of that is you. Nobody else gets to be all of that.",
  ],
  letterSalutation: "Mi Casa,",
  letter: [
    "Happy birthday.",
    "I made this because I wanted you to have something today that was actually yours. Not a message in a chat that scrolls away — something that stays put.",
    "I keep thinking about the calls. You'd fall asleep somewhere in the middle and I'd just leave it running, because having the sound of you in the room was the closest we ever got to being in the same place. Your face when you're asleep is my favorite thing I've never seen in person.",
    "I've told you before that you have snake eyes. I stand by it. And somehow, depending on what you're about to say, they're also the cutest eyes I've ever seen. You can talk your way through any room, and then ask me to fix your assignment at midnight. You have a different voice for every mood and I know which one is coming before you use it. I never got bored of any of it. I never got bored of looking at you.",
    "I'm not going to use your birthday to ask you for anything. You don't owe me a reply to this, or to anything.",
    "But I'd rather say it plainly than make you guess: I love you. That hasn't changed and I'm not expecting it to. I'm still the biggest fan of yours in the entire universe. Whatever this is now — I'm glad it's you on the other end of the line.",
    "Happy birthday, Angel.",
  ],
  signature: "— your player one",
  names: ["Mi Casa.", "Mi Amor.", "Mi Favorito.", "The Angel.", "Baby Angel.", "The one and only."],
  saveLine: "I'd give you my save file.",
} as const;
